// In your main App.jsx or another page component
 import MindMapEditor from './components/MindMapEditor';

// This is the data from the screenshot (or generated by your AI)
const problemSolvingData = {
    id: 'root', text: '8 Step Problem Solving',
    children: [
        { id: '1', text: 'Clarify the problem', children: [{ id: '1.1', text: 'make sure you clearly state the problem and state how it ties to your unit mission' }] },
        { id: '2', text: 'Breakdown the problem', children: [{ id: '2.1', text: 'identify performance gap; what is the current performance compared to desired performance' }] },
        { id: '3', text: 'Set a target', children: [{ id: '3.1', text: 'what level of performance is desired and by when' }] },
        { id: '4', text: 'Analyze the root cause', children: [{ id: '4.1', text: 'get to the level of cause that will ensure the problem does not recur' }] },
        { id: '5', text: 'Develop countermeasures', children: [{ id: '5.1', text: 'identify what specific actions need to be taken to counter the root cause of the problem' }] },
        { id: '6', text: 'See countermeasures through', children: [{ id: '6.1', text: 'follow-up and verify countermeasures are being applied.' }] },
        { id: '7', text: 'Evaluate both results and process', children: [{ id: '7.1', text: 'make sure the countermeasures are providing the results predicted and desired' }] },
        { id: '8', text: 'Standardize successful processes', children: [{ id: '8.1', text: 'share your successes with functionals, make the changes permanent.' }] },
    ]
};

function App() {
    return (
        <div>
            <h1>Interactive Mind Map Editor</h1>
            <MindMapEditor initialData={problemSolvingData} />
        </div>
    );
}

export default App;